# generated by datamodel-codegen:
#   filename:  basemodel_Imitation_Game.json
#   timestamp: 2024-06-07T16:42:32+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Extra


class Player(BaseModel):
    userid: Optional[int] = None
    username: Optional[str] = "null"
    last_message: Optional[str] = "null"
    user_history: Optional[List[str]] = None
    model: Optional[Dict[str, Any]] = None


class Prefixes(Enum):
    PlayerA = "PlayerA"
    PlayerB = "PlayerB"
    PlayerC = "PlayerC"


class MessageWrapper(Enum):
    says = "says"


class VoiceItItems(Enum):
    voice_c_yes = "voice_c_yes"
    voice_b_yes = "voice_b_yes"


class GameStartItems(Enum):
    start_game = "start_game"
    stop_game = "stop_game"


class BaseCommand(Enum):
    start = "start"
    help = "help"


class Game(BaseModel):
    playerA: Optional[Player] = None
    playerB: Optional[Player] = None
    playerC: Optional[Player] = None
    game_chat_id: Optional[int] = None
    last_call: Optional[Dict[str, Any]] = None


class ImitationGame(BaseModel):
    class Config:
        extra = Extra.forbid

    player: Optional[Player] = None
    game: Optional[Game] = None
