# generated by datamodel-codegen:
#   filename:  basemodel_Imitation_Game.json
#   timestamp: 2024-06-07T13:32:59+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Extra


class Player(BaseModel):
    id: Optional[int] = None
    username: Optional[str] = None
    last_message: Optional[str] = None
    user_history: Optional[List[str]] = None


class Prefixes(Enum):
    PlayerA = "PlayerA"
    PlayerB = "PlayerB"
    PlayerC = "PlayerC"


class MessageWrapper(Enum):
    says = "says"


class VoiceItItems(Enum):
    voiceit_item_yes = "voiceit_item_yes"
    voiceit_item_no = "voiceit_item_no"


class GameStartItems(Enum):
    start_game = "start_game"
    stop_game = "stop_game"


class BaseCommand(Enum):
    start = "start"
    help = "help"


class ImitationGame(BaseModel):
    class Config:
        extra = Extra.forbid

    player: Optional[Player] = None
