# This workflow will allows you to deploy to Heroku
# https://github.com/marketplace/actions/deploy-to-heroku
# Procfile - start point
# runtime.txt - python version to run

name: Deploy Heroku

on:
  #  push:
  #    branches: [ "main" ]
  #  pull_request:
  #    branches: [ "main" ]
  workflow_dispatch

jobs:
  build_llama_cpp_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Heroku Action
        uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "llama-cpp-server"
          heroku_email: "epifana89@gmail.com"
          appdir: "llama_cpp_server"
          buildpack: "heroku/python" # "https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git"
          branch: "main"
        env:
          HD_PORT: 8080

  build_ig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Heroku Action
        uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "imitation-game"
          heroku_email: "epifana89@gmail.com"
          appdir: "ig_app"
          buildpack: "heroku/python" # "https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git"
          branch: "main"
        #          healthcheck: "https://imitation-game.herokuapp.com/health"
        env:
          HD_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          HD_DETECT_LANG_API_KEY: ${{secrets.DETECT_LANG_API_KEY}}
